# Generated by Django 4.2.4 on 2023-09-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_fotousers_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotousers',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
