version: "3.9"

services:

  web-server:
    image: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./events/media:/var/www/media/"

    ports:
      - "8000:80"
      - "8443:443"

    depends_on:
      - backend

  database-service:
    image: postgres
    environment:
      POSTGRES_USER: sveta
      POSTGRES_PASSWORD: "sveta"
      POSTGRES_DB: events
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U sveta -d events'"]
      start_period: 5s
      timeout: 10s
      interval: 5s
      retries: 5

    volumes:
      - "./pg_data:/var/lib/postgresql/data"


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sv-maximenko@rambler.ru
      PGADMIN_DEFAULT_PASSWORD: sveta

    ports:
      - "443:443"
      - "80:80"


  backend:
    build: .
    image: events:v4.1
    command: /bin/sh /app/backend.sh

    environment:
      DJANGO_DEBUG: 0
      DJANGO_SECRET_KEY: 'django-insecure-0b_ad5_p++n0169+3d2v4(nkqd@=iy)ykyvus5g6u_nuqa&s7j'
      PG_USER: sveta
      PG_PASSWORD: "sveta"
      PG_NAME: events
      PG_HOST: database-service  # домен (вместо IP)
      PG_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      database-service:
        condition: service_healthy
      redis:
        condition: service_healthy


  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "465:465"


  celery-worker:
    build: .
    image: events:v4.1
    command: celery -A DiplomProject worker -c 2 -l INFO -n worker1

    environment:
      DJANGO_DEBUG: 0
      DJANGO_SECRET_KEY: 'django-insecure-0b_ad5_p++n0169+3d2v4(nkqd@=iy)ykyvus5g6u_nuqa&s7j'
      PG_USER: sveta
      PG_PASSWORD: 'sveta'
      PG_NAME: events
      PG_HOST: database-service  # домен (вместо IP)
      PG_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SIGNING_KEY: u9yw0e9yr12790341927546129n03491023946190263904

    depends_on:
      database-service:
        condition: service_healthy
      redis:
        condition: service_healthy


  celery-beat:
    build: .
    image: events:v4.1
    command: /bin/sh /app/celery-beat.sh

    environment:
      DJANGO_DEBUG: 0
      DJANGO_SECRET_KEY: 'django-insecure-0b_ad5_p++n0169+3d2v4(nkqd@=iy)ykyvus5g6u_nuqa&s7j'
      PG_USER: sveta
      PG_PASSWORD: 'sveta'
      PG_NAME: events
      PG_HOST: database-service  # домен (вместо IP)
      PG_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SIGNING_KEY: u9yw0e9yr12790341927546129n03491023946190263904

    depends_on:
      database-service:
        condition: service_healthy
      redis:
        condition: service_healthy



#  backend1:
#    <<: *backend
#    command: /bin/sh /app/settings/run/backend.sh
#
#
#  backend2:
#    <<: *backend
#    command: /bin/sh /app/settings/run/backend.sh