# Generated by Django 4.2.1 on 2023-06-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default/unAuth.jpg', upload_to='avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
